### ISSUE TITLE
No sent system messages or messages from the item Jenkins

### ISSUE THREAD

**Issue by HarryHoudini** [jenkinsci/telegram-notifications-plugin#30]
I added to the field Telegram Bot name, Telegram Bot token, but I don't get system messages or messages from the item Jenkins. 
Environment: 
Ubuntu 16.04, 
Jenkins ver. 2.138.1
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

In the Jenkins log I see the massange below: 

`Oct 05, 2018 11:35:46 AM INFO jenkinsci.plugins.telegrambot.telegram.TelegramBot initializeProxy
 
Proxy successfully initialized
 
Oct 05, 2018 11:35:46 AM INFO jenkinsci.plugins.telegrambot.telegram.TelegramBotRunner lambda$new$1
 
Bot was created
 
Oct 05, 2018 11:35:46 AM SEVERE jenkinsci.plugins.telegrambot.telegram.TelegramBotRunner createBotSession
 
Telegram API error
javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied
  at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
  at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
  at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2038)
  at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
  at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
  at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
  at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
  at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:43)
Caused: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error executing setWebook method
  at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:55)
  at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120)
  at jenkinsci.plugins.telegrambot.telegram.TelegramBotRunner.createBotSession(TelegramBotRunner.java:84)
  at jenkinsci.plugins.telegrambot.telegram.TelegramBotRunner.lambda$new$1(TelegramBotRunner.java:75)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)`

**Comment by HarryHoudini** [comment]
This message disappeared when I turned on using a non-Russian proxy.
