### ISSUE TITLE
Message do not sended. [400] Bad Request: can't parse entities

### ISSUE THREAD

**Issue by mausspb** [jenkinsci/telegram-notifications-plugin#33]
I get error Jenkins log all.
Message do not sended.
I'm not use mardown, simple Letter and number, like `Version = ${version_parametr}`, in log job i see `Version = 123`, but in log jenkins i see next error:
`org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 133
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.sendApiMethodWithProxy(TelegramBot.java:222)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.execute(TelegramBot.java:153)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.sendMessage(TelegramBot.java:80)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.lambda$sendMessage$0(TelegramBot.java:102)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.sendMessage(TelegramBot.java:102)
	at jenkinsci.plugins.telegrambot.TelegramBotBuilder.perform(TelegramBotBuilder.java:63)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)`

**Comment by nikitabelonogov** [comment]
Hi @mausspb 

How do you set _version_parametr_ in build environment?

**Comment by mausspb** [comment]
`test/deafult_build`

**Comment by mausspb** [comment]
I think troubl was from whitespace in end of line in the body

**Comment by mausspb** [comment]
Bug reproduced again with other data ....
Jenkins log, version 1.2.1

---

```
########################
   App               :: *app*
   Env                :: stage_app
   Status build :: *SUCCESS* ✅
########################

Git commit id      :: b0a42b5f
Git commit desc :: Y1-000

Job Name          :: experiments/Auth
Job id jenkins    :: 001
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 84
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.sendApiMethodWithProxy(TelegramBot.java:222)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.execute(TelegramBot.java:153)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.sendMessage(TelegramBot.java:80)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.lambda$sendMessage$0(TelegramBot.java:102)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBot.sendMessage(TelegramBot.java:102)
	at jenkinsci.plugins.telegrambot.TelegramBotBuilder.perform(TelegramBotBuilder.java:63)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

**Comment by mausspb** [comment]
I found problem [here](https://github.com/lukefx/hubot-telegram/issues/57#issuecomment-274494625), with again - markdown. May be you implement the code for check in markdown ? Or this is already implements in new version?

**Comment by zerthimon** [comment]
This is happening because of underscore char.
What if you cannot escape it, for example when it comes in a variable, such as ${RUN_DISPLAY_URL} ?
The plugin needs to add a way to handle this!
