### ISSUE TITLE
Error removing old webhook

### ISSUE THREAD

**Issue by mausspb** [jenkinsci/telegram-notifications-plugin#34]
Error in last 1.3.0 version 
What is this error about?

```Telegram API error
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error removing old webhook: [404] Not Found
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:49)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBotRunner.createBotSession(TelegramBotRunner.java:66)
	at jenkinsci.plugins.telegrambot.telegram.TelegramBotRunner.lambda$new$0(TelegramBotRunner.java:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mausspb** [comment]
Settings for bot ( token and name) was cleared.
I filled it again, but no response in tg not . 
/start and /help not interactive

**Comment by vikulin** [comment]
It seems your Telegram token is incorrect

**Comment by amezin** [comment]
I've been getting 404 errors too. I've updated TelegramBots library in https://github.com/jenkinsci/telegram-notifications-plugin/pull/51 but, unfortunately, there is still no release of the plugin with these changes. I'm currently using my own build of the plugin from master branch, and it is working fine. You could ask @nikitabelonogov to do a release

**Comment by amezin** [comment]
Oh, this is an ancient issue (but I somehow received a notification about it), so likely it's unrelated. A new release would still be a good idea though.
