### ISSUE TITLE
Invalid parameter "chatId"

### ISSUE THREAD

**Issue by nnhiep** [jenkinsci/telegram-notifications-plugin#53]
I tried using chaId to send multiple groups. The syntax is as below. 
            telegramSend(message: 'Test', chatId: xxxx)
I have received the error: Invalid parameter "chatId".
who can help me?

**Comment by bthompson0** [comment]
@nnhiep I think it should be `chat_id` instead of `chatId` since TelegramBots is [favoring snake case deserialization](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/api/methods/send/SendMessage.java#L27).

**Comment by 4n70w4** [comment]
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 84: Invalid parameter "chat_id", did you mean "chatId"? @ line 84, column 84.
   AME} ${JOB_NAME} ${JOB_URL}', chat_id: -
                                 ^

WorkflowScript: 98: Invalid parameter "chat_id", did you mean "chatId"? @ line 98, column 83.
   AME} ${JOB_NAME} ${JOB_URL}', chat_id: -
                                 ^

2 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```
