### ISSUE TITLE
jenkins.plugins.telegram.endpoint.TelegramBot$1 onGetUpdatesFailure

### ISSUE THREAD

**Issue by muhammedfarahat-kg** [jenkinsci/telegram-notifications-plugin#56]
Getting (literally) millions of error messages in Jenkins log file located in /var/log/jenkins/jenkins.log

As the following:
```
WARNING: exception occured while processing updates from telegram
org.apache.commons.httpclient.HttpException: call to telegram returned unexpected http status code 404
        at jenkins.plugins.telegram.TelegramService.getRawUpdate(TelegramService.java:83)
        at jenkins.plugins.telegram.bot.polling.TelegramLongPoller.getNewUpdates(TelegramLongPoller.java:76)
        at jenkins.plugins.telegram.bot.polling.TelegramLongPoller.run(TelegramLongPoller.java:53)
```

Jenkins crashed a couple of times in the last month, and I suspect it's because of the log file getting oversized (reaching ~8GB) because of this error message

**Comment by bthompson0** [comment]
Which version of the plugin are you using?

**Comment by muhammedfarahat-kg** [comment]
3.2.1

**Comment by muhammedfarahat-kg** [comment]
@bthompson0 3.2.1

**Comment by bthompson0** [comment]
1.4.0 is the latest release of this plugin.  By the looks of the stack trace it looks like a completely different plugin.

**Comment by muhammedfarahat-kg** [comment]
you are totally right, seems like it's a different plugin - it was confusing because the name of this repository is named after the plugin I am using. Although it's different, apparently.

<img width="1288" alt="Screenshot 2020-05-26 at 15 35 34" src="https://user-images.githubusercontent.com/56540205/82907299-b9beef00-9f66-11ea-9438-0f32fbd9dae5.png">

**Comment by bthompson0** [comment]
It is confusing... especially since they're both under the same namespace.  I searched in the Jenkins public Artifactory repository and wasn't able to find the plugin you are using. :(

**Comment by bthompson0** [comment]
Correction, they are under a slightly different namespace. `jenkins` vs. `org.jenkins-ci`.
