### ISSUE TITLE
Error sending message: [400] Bad Request: message is too long

### ISSUE THREAD

**Issue by rus364** [jenkinsci/telegram-notifications-plugin#69]
Good day.

I got an error below when the plugin tried to send a message:

```
Error sending message
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: message is too long
        at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
        at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
        at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:689)
        at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53)
        at com.itransition.iam.telegram.bots.JiraBot$sendMsg$1.run(JiraBot.kt:332)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Plugin version:

```
0.9.14
```

**Comment by maks-rafalko** [comment]
Please explain what was the issue for future visitors. Thank you.
