### ISSUE TITLE
 I don't understand how to make the plugin work

### ISSUE THREAD

**Issue by Ka1va** [jenkinsci/telegram-notifications-plugin#77]
### What feature do you want to see added?

here is my pipeline
![Screenshot from 2024-04-24 15-19-49](https://github.com/jenkinsci/telegram-notifications-plugin/assets/164864999/13d36fdb-0e54-46ca-92d3-b5bd5f0fccab)
here is my plugin settings
![Screenshot from 2024-04-24 15-22-28](https://github.com/jenkinsci/telegram-notifications-plugin/assets/164864999/93c1065a-22cb-4f49-85f9-8e91b36654ef)

**Comment by Ka1va** [comment]
Please explain what's wrong

**Comment by justbelieveinmyself** [comment]
You should review the jenkins logs

**Comment by peterarsentev** [comment]
@Ka1va If you don't mind, I'd like to help you out as I've had to deal with this plugin recently.
Some configurations are a little tricky to overlook.
First of all, after installing this plugin, you need to go into the system config and look up the block telegram.
There you will find the field name where you need to enter the name of your bot starting with @.
Like this @job4j_bot.
Then you have to specify TOKEN. 
I then restarted jenkins as I did not see any changes in the system log.
So all you have to do now is add notification lines to your pipeline script.
```
     post {
        always {
           telegramSend "Build number: ${currentBuild.number}"
           telegramSend "Build status: ${currentBuild.currentResult}"
           telegramSend "Started at: ${new Date(currentBuild.startTimeInMillis)}"
           telegramSend "Duration so far: ${currentBuild.durationString}"
           telegramSend "The build was triggered by: ${currentBuild.getBuildCauses()}"
        }
    }   
```
Then I run my pipeline and get the first message in telegram, it makes me so happy.

**Comment by JoshuaSeidel** [comment]
@peterarsentev 

im having this issue, followed your suggestions and i got this

```2025-01-21 21:30:40.334+0000 [id=2269]  SEVERE  j.p.t.telegram.TelegramBot#expandMessage: Error while expanding the message
org.jenkinsci.plugins.tokenmacro.MacroEvaluationException: Unrecognized macro 'UserIdCause' in 'The build was triggered by: [[_class:hudson.model.Cause$UserIdCause, shortDescription:Started by user anonymous, userId:null, userName:anonymous]]'
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.Parser.processToken(Parser.java:492)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.Parser.parseNonDelimitedToken(Parser.java:186)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.Parser.parseToken(Parser.java:113)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.Parser.parse(Parser.java:87)
Caused: org.jenkinsci.plugins.tokenmacro.MacroEvaluationException: Error processing tokens
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.Parser.parse(Parser.java:97)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:75)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.Parser.process(Parser.java:68)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.TokenMacro.expand(TokenMacro.java:196)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:234)
        at PluginClassLoader for token-macro//org.jenkinsci.plugins.tokenmacro.TokenMacro.expandAll(TokenMacro.java:204)
        at PluginClassLoader for telegram-notifications//jenkinsci.plugins.telegrambot.telegram.TelegramBot.expandMessage(TelegramBot.java:92)
        at PluginClassLoader for telegram-notifications//jenkinsci.plugins.telegrambot.telegram.TelegramBot.sendMessage(TelegramBot.java:104)
        at PluginClassLoader for telegram-notifications//jenkinsci.plugins.telegrambot.TelegramBotMessager.perform(TelegramBotMessager.java:71)
        at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
        at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:101)
        at PluginClassLoader for workflow-basic-steps//org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
        at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by peterarsentev** [comment]
@Ka1va 
I think you are trying to run your pipeline as anonymous. Try logging in and running your pipeline as the current user. 
This will reduce the number of problem fields.
